title: highunder
url: "https://highunder.github.io/"

plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
markdown: kramdown
collections:
  my_tags:
    output: true
    permalink: /tagged/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: tagged
permalink: /blog/:slug
timezone: Japan/Tokyo
future: false
